---
storage:
  stoage_account_name: advj8385
  storage_account_key: atLNozj3iklKa8qD0gYU856NR1y1ydFf3F7mPZxyty7TEOq1jgNcqyPJpSX+Bid2H/1WkKkZSgna+ASt+SPymg==
db:
  conn_str: Server=10.10.132.12;Database=myDataBase;User Id=myUsername;Password=myComplexPass;
